service: procurment
frameworkVersion: '3'

provider:
  name: aws
  stage: dev
  timeout: 15
  runtime: nodejs14.x
  region: us-east-1

functions:
  AddRequest:
    handler: add_request.add_request 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeleteRequest:
    handler: delete_request.delete_request 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchRequest:
    handler: search_request.search_request 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdateRequest:
    handler: upadte_request.upadte_request 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivateRequest:
    handler: deactivate_request.deactivate_request 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw


  AddSupplier:
    handler: add_supplier.add_supplier 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeleteSupplier:
    handler: delete_supplier.delete_supplier 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchSupplier:
    handler: search_supplier.search_supplier 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdateSupplier:
    handler: upadte_supplier.upadte_supplier 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivateSupplier:
    handler: deactivate_supplier.deactivate_supplier 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw



  AddProduct:
    handler: add_product.add_product 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeleteProduct:
    handler: delete_product.delete_product 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchProduct:
    handler: search_product.search_product 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdateProduct:
    handler: upadte_product.upadte_product 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivateProduct:
    handler: deactivate_product.deactivate_product 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw


  AddCurrency:
    handler: add_currency.add_currency 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeleteCurrency:
    handler: delete_currency.delete_currency 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchCurrency:
    handler: search_currency.search_currency 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdateCurrency:
    handler: upadte_currency.upadte_currency 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivateCurrency:
    handler: deactivate_currency.deactivate_currency 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw

  AddInvoice:
    handler: add_invoice.add_invoice 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeleteInvoice:
    handler: delete_invoice.delete_invoice 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchInvoice:
    handler: search_invoice.search_invoice 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdateInvoice:
    handler: upadte_invoice.upadte_invoice 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivateInvoice:
    handler: deactivate_invoice.deactivate_invoice 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw


  AddPurchaseOrder:
    handler: add_purchase_order.add_purchase_order 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeletePurchaseOrder:
    handler: delete_purchase_order.delete_purchase_order 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchPurchaseOrder:
    handler: search_purchase_order.search_purchase_order 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdatePurchaseOrder:
    handler: upadte_purchase_order.upadte_purchase_order 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivatePurchaseOrder:
    handler: deactivate_purchase_order.deactivate_purchase_order 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw


  ApproveRequest:
    handler: approve_request.approve_request 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw

  AddQuotation:
    handler: add_quotation.add_quotation 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeleteQuotation:
    handler: delete_quotation.delete_quotation 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  SearchQuotation:
    handler: search_quotation.search_quotation 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  UpdateQuotation:
    handler: upadte_quotation.upadte_quotation 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
  DeactivateQuotation:
    handler: deactivate_quotation.deactivate_quotation 
    role: arn:aws:iam::657907747545:role/service-role/StepFunction_uc1_Requirement-role-2coy70yw
