service: procurement
frameworkVersion: '3'

useDotenv: true

plugins: 
  - serverless-offline

provider:
  name: aws
  stage: dev
  timeout: 15
  runtime: nodejs14.x
  region: us-east-1


functions:

  # Request configuration
  # Add request
  AddRequest:
    handler: request/add_request.add_request 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /request
        method: post
        cors: true
     
  # Delete request
  DeleteRequest:
    handler: request/delete_request.delete_request 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /request/{id}
        method: delete
        cors: true
        
  # Search request
  SearchRequest:
    handler: request/search_request.search_request 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /request
        method: get
        cors: true

  # Update request
  UpdateRequest:
    handler: request/upadte_request.upadte_request 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /request/{id}
        method: put
        cors: true
        
  # Deactivate request
  DeactivateRequest:
    handler: request/deactivate_request.deactivate_request 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /request/deactivate/{id}
        method: post
        cors: true
      
  # Approve request
  ApproveRequest:
    handler: request/approve_request.approve_request 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /request/approve/{id}
        method: post
        cors: true
       

  # Supplier configuration
  # Add supplier
  AddSupplier:
    handler: supplier/add_supplier.add_supplier 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /supplier
        method: post
        cors: true

  # Delete supplier
  DeleteSupplier:
    handler: supplier/delete_supplier.delete_supplier 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /supplier/{id}
        method: delete
        cors: true

  # Search supplier
  SearchSupplier:
    handler: supplier/search_supplier.search_supplier 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /supplier
        method: get
        cors: true

  # Update supplier
  UpdateSupplier:
    handler: supplier/upadte_supplier.upadte_supplier 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /supplier/{id}
        method: put
        cors: true

  # Deactivate Supplier
  DeactivateSupplier:
    handler: supplier/deactivate_supplier.deactivate_supplier 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /supplier/deactivate/{id}
        method: post
        cors: true


  # Product configuration
  # Add product
  AddProduct:
    handler: product/add_product.add_product 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /product
        method: post
        cors: true

  # Delete product
  DeleteProduct:
    handler: product/delete_product.delete_product 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /product/{id}
        method: delete
        cors: true
    
  # Search product
  SearchProduct:
    handler: product/search_product.search_product 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /product
        method: get
        cors: true

  # Update product
  UpdateProduct:
    handler: product/upadte_product.upadte_product 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /product/{id}
        method: put
        cors: true

  # Deactivate product
  DeactivateProduct:
    handler: product/deactivate_product.deactivate_product 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /product/deactivate/{id}
        method: post
        cors: true


  # Currency configuration
  # Add currency
  AddCurrency:
    handler: currency/add_currency.add_currency 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /currency
        method: post
        cors: true
       
  # Delete currency
  DeleteCurrency:
    handler: currency/delete_currency.delete_currency 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /currency/{id}
        method: delete
        cors: true

  # Search currency
  SearchCurrency:
    handler: currency/search_currency.search_currency 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /currency
        method: get
        cors: true

  # Update currency
  UpdateCurrency:
    handler: currency/upadte_currency.upadte_currency 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /currency/{id}
        method: put
        cors: true

  # Deactivate currency
  DeactivateCurrency:
    handler: currency/deactivate_currency.deactivate_currency 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /currency/deactivate/{id}
        method: post
        cors: true


  #  Invoice configuration
  # Add invoice
  AddInvoice:
    handler: invoice/add_invoice.add_invoice 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /invoice
        method: post
        cors: true

  # Delete invoice
  DeleteInvoice:
    handler: invoice/delete_invoice.delete_invoice 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /invoice/{id}
        method: delete
        cors: true

  # Search invoice
  SearchInvoice:
    handler: invoice/search_invoice.search_invoice 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /invoice
        method: get
        cors: true

  # Update invoice
  UpdateInvoice:
    handler: invoice/upadte_invoice.upadte_invoice 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /invoice/{id}
        method: put
        cors: true

  # Deactivate invoice
  DeactivateInvoice:
    handler: invoice/deactivate_invoice.deactivate_invoice 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /invoice/deactivate/{id}
        method: post
        cors: true


  # Purchase Order configuration
  # Add purchase_order
  AddPurchaseOrder:
    handler: purchase_order/add_purchase_order.add_purchase_order 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /purchase_order
        method: post
        cors: true

  # Delete purchase_order
  DeletePurchaseOrder:
    handler: purchase_order/delete_purchase_order.delete_purchase_order 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /purchase_order/{id}
        method: delete
        cors: true
    
  # Search purchase_order
  SearchPurchaseOrder:
    handler: purchase_order/search_purchase_order.search_purchase_order 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /purchase_order
        method: get
        cors: true

  # Update purchase_order
  UpdatePurchaseOrder:
    handler: purchase_order/upadte_purchase_order.upadte_purchase_order 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /purchase_order/{id}
        method: put
        cors: true
  
  # Deactivate purchase_order
  DeactivatePurchaseOrder:
    handler: purchase_order/deactivate_purchase_order.deactivate_purchase_order 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /purchase_order/deactivate/{id}
        method: post
        cors: true


  # Quotation configuration
  # Add quotation
  AddQuotation:
    handler: quotation/add_quotation.add_quotation 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /quotation
        method: post
        cors: true

  # Delete quotation
  DeleteQuotation:
    handler: quotation/delete_quotation.delete_quotation 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /quotation/{id}
        method: delete
        cors: true

  # Search quotation
  SearchQuotation:
    handler: quotation/search_quotation.search_quotation 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /quotation
        method: get
        cors: true

  # Update quotation
  UpdateQuotation:
    handler: quotation/upadte_quotation.upadte_quotation 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /quotation/{id}
        method: put
        cors: true

  # Deactivate quotation
  DeactivateQuotation:
    handler: quotation/deactivate_quotation.deactivate_quotation 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /quotation/deactivate/{id}
        method: post
        cors: true


  # Approvers configuration
  # Add approvers
  AddApprovers:
    handler: approvers/add_approvers.add_approvers 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /approvers
        method: post
        cors: true

  # Delete approvers
  DeleteApprovers:
    handler: approvers/delete_approvers.delete_approvers 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /approvers/{id}
        method: delete
        cors: true

  # Search approvers
  SearchApprovers:
    handler: approvers/search_approvers.search_approvers 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /approvers
        method: get
        cors: true

  # Update approvers
  UpdateApprovers:
    handler: approvers/upadte_approvers.upadte_approvers
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /approvers/{id}
        method: put
        cors: true


  # Company profile
  # Add company_profile
  AddCompanyProfile:
    handler: company_profile/add_company_profile.add_company_profile 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /company_profile
        method: post
        cors: true

  # Delete company_profile
  DeleteCompanyProfile:
    handler: company_profile/delete_company_profile.delete_company_profile 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /company_profile/{id}
        method: delete
        cors: true

  # Search company_profile
  SearchCompanyProfile:
    handler: company_profile/search_company_profile.search_company_profile 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /company_profile
        method: get
        cors: true

  # Update company_profile
  UpdateCompanyProfile:
    handler: company_profile/upadte_company_profile.upadte_company_profile
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /company_profile/{id}
        method: put
        cors: true

  # Deactivate company_profile
  DeactivateCompanyProfile:
    handler: company_profile/deactivate_company_profile.deactivate_company_profile 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /company_profile/deactivate/{id}
        method: post
        cors: true


  # department configuration
  # Add department
  AddDepartment:
    handler: department/add_department.add_department 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /department
        method: post
        cors: true

  # Delete department
  DeleteDepartment:
    handler: department/delete_department.delete_department 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /department/{id}
        method: delete
        cors: true

  # Search department
  SearchDepartment:
    handler: department/search_department.search_department 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /department
        method: get
        cors: true

  # Update department
  UpdateDepartment:
    handler: department/update_department.upadte_department 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /department/{id}
        method: put
        cors: true

  # Deactivate department
  DeactivateDepartment:
    handler: department/deactivate_department.deactivate_department 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /department/deactivate/{id}
        method: post
        cors: true


  # contact configuration
  # Add contact
  AddContact:
    handler: contact/add_contact.add_contact 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /contact
        method: post
        cors: true

  # Delete contact
  DeleteContact:
    handler: contact/delete_contact.delete_contact 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /contact/{id}
        method: delete
        cors: true

  # Search contact
  SearchContact:
    handler: contact/search_contact.search_contact 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /contact
        method: get
        cors: true

  # Update contact
  UpdateContact:
    handler: contact/update_contact.upadte_contact 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /contact/{id}
        method: put
        cors: true

  # Deactivate contact
  DeactivateContact:
    handler: contact/deactivate_contact.deactivate_contact 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /contact/deactivate/{id}
        method: post
        cors: true


  # notification configuration
  # Add notification
  AddNotification:
    handler: notification/add_notification.add_notification 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /notification
        method: post
        cors: true

  # Delete notification
  DeleteNotification:
    handler: notification/delete_notification.delete_notification 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /notification/{id}
        method: delete
        cors: true

  # Search notification
  SearchNotification:
    handler: notification/search_notification.search_notification 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /notification
        method: get
        cors: true

  # Update notification
  UpdateNotification:
    handler: notification/update_notification.upadte_notification 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /notification/{id}
        method: put
        cors: true

  # Deactivate notification
  DeactivateNotification:
    handler: notification/deactivate_notification.deactivate_notification 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /notification/deactivate/{id}
        method: post
        cors: true


  # Email configuration
  # Search emails
  SearchSentEmails:
    handler: email/search_sent_emails.search_sent_emails 
    role: ${env:LAMBDA_ROLE}
    events:
    - http:
        path: /email
        method: get
        cors: true
